//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vp_webservice_documenttasks
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/TaskQueues/v1/")]
    public partial class Authorization
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/TaskQueues/v1/")]
    public partial class TaskQueueEntry
    {
        
        private long queueEntryIdField;
        
        private long documentIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long queueEntryId
        {
            get
            {
                return this.queueEntryIdField;
            }
            set
            {
                this.queueEntryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long documentId
        {
            get
            {
                return this.documentIdField;
            }
            set
            {
                this.documentIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/TaskQueues/v1/")]
    public partial class InvalidArgument
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/TaskQueues/v1/")]
    public partial class Authentication
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/TaskQueues/v1/", ConfigurationName="vp_webservice_documenttasks.TaskQueues")]
    public interface TaskQueues
    {
        
        // CODEGEN: Parameter 'taskQueueEntry' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documenttasks.Authorization), Action="", Name="Authorization")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documenttasks.InvalidArgument), Action="", Name="InvalidArgument")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documenttasks.Authentication), Action="", Name="Authentication")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="taskQueueEntry")]
        vp_webservice_documenttasks.getNextEntryInTaskQueueResponse getNextEntryInTaskQueue(vp_webservice_documenttasks.getNextEntryInTaskQueue request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<vp_webservice_documenttasks.getNextEntryInTaskQueueResponse> getNextEntryInTaskQueueAsync(vp_webservice_documenttasks.getNextEntryInTaskQueue request);
        
        // CODEGEN: Parameter 'taskQueueEntry' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documenttasks.Authorization), Action="", Name="Authorization")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documenttasks.InvalidArgument), Action="", Name="InvalidArgument")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documenttasks.Authentication), Action="", Name="Authentication")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="taskQueueEntry")]
        vp_webservice_documenttasks.getNextEntryInTaskQueueByNodeResponse getNextEntryInTaskQueueByNode(vp_webservice_documenttasks.getNextEntryInTaskQueueByNode request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<vp_webservice_documenttasks.getNextEntryInTaskQueueByNodeResponse> getNextEntryInTaskQueueByNodeAsync(vp_webservice_documenttasks.getNextEntryInTaskQueueByNode request);
        
        // CODEGEN: Parameter 'sessionId' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documenttasks.Authorization), Action="", Name="Authorization")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documenttasks.InvalidArgument), Action="", Name="InvalidArgument")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documenttasks.Authentication), Action="", Name="Authentication")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        vp_webservice_documenttasks.setEntryProcessedFailResponse setEntryProcessedFail(vp_webservice_documenttasks.setEntryProcessedFail request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<vp_webservice_documenttasks.setEntryProcessedFailResponse> setEntryProcessedFailAsync(vp_webservice_documenttasks.setEntryProcessedFail request);
        
        // CODEGEN: Parameter 'sessionId' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documenttasks.Authorization), Action="", Name="Authorization")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documenttasks.InvalidArgument), Action="", Name="InvalidArgument")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documenttasks.Authentication), Action="", Name="Authentication")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        vp_webservice_documenttasks.setEntryProcessedSuccessResponse setEntryProcessedSuccess(vp_webservice_documenttasks.setEntryProcessedSuccess request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<vp_webservice_documenttasks.setEntryProcessedSuccessResponse> setEntryProcessedSuccessAsync(vp_webservice_documenttasks.setEntryProcessedSuccess request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNextEntryInTaskQueue", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/TaskQueues/v1/", IsWrapped=true)]
    public partial class getNextEntryInTaskQueue
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/TaskQueues/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/TaskQueues/v1/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string queueName;
        
        public getNextEntryInTaskQueue()
        {
        }
        
        public getNextEntryInTaskQueue(string sessionId, string queueName)
        {
            this.sessionId = sessionId;
            this.queueName = queueName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNextEntryInTaskQueueResponse", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/TaskQueues/v1/", IsWrapped=true)]
    public partial class getNextEntryInTaskQueueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/TaskQueues/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public vp_webservice_documenttasks.TaskQueueEntry taskQueueEntry;
        
        public getNextEntryInTaskQueueResponse()
        {
        }
        
        public getNextEntryInTaskQueueResponse(vp_webservice_documenttasks.TaskQueueEntry taskQueueEntry)
        {
            this.taskQueueEntry = taskQueueEntry;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNextEntryInTaskQueueByNode", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/TaskQueues/v1/", IsWrapped=true)]
    public partial class getNextEntryInTaskQueueByNode
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/TaskQueues/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/TaskQueues/v1/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string queueName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/TaskQueues/v1/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nodeName;
        
        public getNextEntryInTaskQueueByNode()
        {
        }
        
        public getNextEntryInTaskQueueByNode(string sessionId, string queueName, string nodeName)
        {
            this.sessionId = sessionId;
            this.queueName = queueName;
            this.nodeName = nodeName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNextEntryInTaskQueueByNodeResponse", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/TaskQueues/v1/", IsWrapped=true)]
    public partial class getNextEntryInTaskQueueByNodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/TaskQueues/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public vp_webservice_documenttasks.TaskQueueEntry taskQueueEntry;
        
        public getNextEntryInTaskQueueByNodeResponse()
        {
        }
        
        public getNextEntryInTaskQueueByNodeResponse(vp_webservice_documenttasks.TaskQueueEntry taskQueueEntry)
        {
            this.taskQueueEntry = taskQueueEntry;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setEntryProcessedFail", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/TaskQueues/v1/", IsWrapped=true)]
    public partial class setEntryProcessedFail
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/TaskQueues/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/TaskQueues/v1/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long queueEntryId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/TaskQueues/v1/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errorMessage;
        
        public setEntryProcessedFail()
        {
        }
        
        public setEntryProcessedFail(string sessionId, long queueEntryId, string errorMessage)
        {
            this.sessionId = sessionId;
            this.queueEntryId = queueEntryId;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setEntryProcessedFailResponse", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/TaskQueues/v1/", IsWrapped=true)]
    public partial class setEntryProcessedFailResponse
    {
        
        public setEntryProcessedFailResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setEntryProcessedSuccess", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/TaskQueues/v1/", IsWrapped=true)]
    public partial class setEntryProcessedSuccess
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/TaskQueues/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/TaskQueues/v1/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long queueEntryId;
        
        public setEntryProcessedSuccess()
        {
        }
        
        public setEntryProcessedSuccess(string sessionId, long queueEntryId)
        {
            this.sessionId = sessionId;
            this.queueEntryId = queueEntryId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setEntryProcessedSuccessResponse", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/TaskQueues/v1/", IsWrapped=true)]
    public partial class setEntryProcessedSuccessResponse
    {
        
        public setEntryProcessedSuccessResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface TaskQueuesChannel : vp_webservice_documenttasks.TaskQueues, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class TaskQueuesClient : System.ServiceModel.ClientBase<vp_webservice_documenttasks.TaskQueues>, vp_webservice_documenttasks.TaskQueues
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TaskQueuesClient() : 
                base(TaskQueuesClient.GetDefaultBinding(), TaskQueuesClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.TaskQueuesPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TaskQueuesClient(EndpointConfiguration endpointConfiguration) : 
                base(TaskQueuesClient.GetBindingForEndpoint(endpointConfiguration), TaskQueuesClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TaskQueuesClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TaskQueuesClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TaskQueuesClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TaskQueuesClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TaskQueuesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        vp_webservice_documenttasks.getNextEntryInTaskQueueResponse vp_webservice_documenttasks.TaskQueues.getNextEntryInTaskQueue(vp_webservice_documenttasks.getNextEntryInTaskQueue request)
        {
            return base.Channel.getNextEntryInTaskQueue(request);
        }
        
        public vp_webservice_documenttasks.TaskQueueEntry getNextEntryInTaskQueue(string sessionId, string queueName)
        {
            vp_webservice_documenttasks.getNextEntryInTaskQueue inValue = new vp_webservice_documenttasks.getNextEntryInTaskQueue();
            inValue.sessionId = sessionId;
            inValue.queueName = queueName;
            vp_webservice_documenttasks.getNextEntryInTaskQueueResponse retVal = ((vp_webservice_documenttasks.TaskQueues)(this)).getNextEntryInTaskQueue(inValue);
            return retVal.taskQueueEntry;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<vp_webservice_documenttasks.getNextEntryInTaskQueueResponse> vp_webservice_documenttasks.TaskQueues.getNextEntryInTaskQueueAsync(vp_webservice_documenttasks.getNextEntryInTaskQueue request)
        {
            return base.Channel.getNextEntryInTaskQueueAsync(request);
        }
        
        public System.Threading.Tasks.Task<vp_webservice_documenttasks.getNextEntryInTaskQueueResponse> getNextEntryInTaskQueueAsync(string sessionId, string queueName)
        {
            vp_webservice_documenttasks.getNextEntryInTaskQueue inValue = new vp_webservice_documenttasks.getNextEntryInTaskQueue();
            inValue.sessionId = sessionId;
            inValue.queueName = queueName;
            return ((vp_webservice_documenttasks.TaskQueues)(this)).getNextEntryInTaskQueueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        vp_webservice_documenttasks.getNextEntryInTaskQueueByNodeResponse vp_webservice_documenttasks.TaskQueues.getNextEntryInTaskQueueByNode(vp_webservice_documenttasks.getNextEntryInTaskQueueByNode request)
        {
            return base.Channel.getNextEntryInTaskQueueByNode(request);
        }
        
        public vp_webservice_documenttasks.TaskQueueEntry getNextEntryInTaskQueueByNode(string sessionId, string queueName, string nodeName)
        {
            vp_webservice_documenttasks.getNextEntryInTaskQueueByNode inValue = new vp_webservice_documenttasks.getNextEntryInTaskQueueByNode();
            inValue.sessionId = sessionId;
            inValue.queueName = queueName;
            inValue.nodeName = nodeName;
            vp_webservice_documenttasks.getNextEntryInTaskQueueByNodeResponse retVal = ((vp_webservice_documenttasks.TaskQueues)(this)).getNextEntryInTaskQueueByNode(inValue);
            return retVal.taskQueueEntry;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<vp_webservice_documenttasks.getNextEntryInTaskQueueByNodeResponse> vp_webservice_documenttasks.TaskQueues.getNextEntryInTaskQueueByNodeAsync(vp_webservice_documenttasks.getNextEntryInTaskQueueByNode request)
        {
            return base.Channel.getNextEntryInTaskQueueByNodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<vp_webservice_documenttasks.getNextEntryInTaskQueueByNodeResponse> getNextEntryInTaskQueueByNodeAsync(string sessionId, string queueName, string nodeName)
        {
            vp_webservice_documenttasks.getNextEntryInTaskQueueByNode inValue = new vp_webservice_documenttasks.getNextEntryInTaskQueueByNode();
            inValue.sessionId = sessionId;
            inValue.queueName = queueName;
            inValue.nodeName = nodeName;
            return ((vp_webservice_documenttasks.TaskQueues)(this)).getNextEntryInTaskQueueByNodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        vp_webservice_documenttasks.setEntryProcessedFailResponse vp_webservice_documenttasks.TaskQueues.setEntryProcessedFail(vp_webservice_documenttasks.setEntryProcessedFail request)
        {
            return base.Channel.setEntryProcessedFail(request);
        }
        
        public void setEntryProcessedFail(string sessionId, long queueEntryId, string errorMessage)
        {
            vp_webservice_documenttasks.setEntryProcessedFail inValue = new vp_webservice_documenttasks.setEntryProcessedFail();
            inValue.sessionId = sessionId;
            inValue.queueEntryId = queueEntryId;
            inValue.errorMessage = errorMessage;
            vp_webservice_documenttasks.setEntryProcessedFailResponse retVal = ((vp_webservice_documenttasks.TaskQueues)(this)).setEntryProcessedFail(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<vp_webservice_documenttasks.setEntryProcessedFailResponse> vp_webservice_documenttasks.TaskQueues.setEntryProcessedFailAsync(vp_webservice_documenttasks.setEntryProcessedFail request)
        {
            return base.Channel.setEntryProcessedFailAsync(request);
        }
        
        public System.Threading.Tasks.Task<vp_webservice_documenttasks.setEntryProcessedFailResponse> setEntryProcessedFailAsync(string sessionId, long queueEntryId, string errorMessage)
        {
            vp_webservice_documenttasks.setEntryProcessedFail inValue = new vp_webservice_documenttasks.setEntryProcessedFail();
            inValue.sessionId = sessionId;
            inValue.queueEntryId = queueEntryId;
            inValue.errorMessage = errorMessage;
            return ((vp_webservice_documenttasks.TaskQueues)(this)).setEntryProcessedFailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        vp_webservice_documenttasks.setEntryProcessedSuccessResponse vp_webservice_documenttasks.TaskQueues.setEntryProcessedSuccess(vp_webservice_documenttasks.setEntryProcessedSuccess request)
        {
            return base.Channel.setEntryProcessedSuccess(request);
        }
        
        public void setEntryProcessedSuccess(string sessionId, long queueEntryId)
        {
            vp_webservice_documenttasks.setEntryProcessedSuccess inValue = new vp_webservice_documenttasks.setEntryProcessedSuccess();
            inValue.sessionId = sessionId;
            inValue.queueEntryId = queueEntryId;
            vp_webservice_documenttasks.setEntryProcessedSuccessResponse retVal = ((vp_webservice_documenttasks.TaskQueues)(this)).setEntryProcessedSuccess(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<vp_webservice_documenttasks.setEntryProcessedSuccessResponse> vp_webservice_documenttasks.TaskQueues.setEntryProcessedSuccessAsync(vp_webservice_documenttasks.setEntryProcessedSuccess request)
        {
            return base.Channel.setEntryProcessedSuccessAsync(request);
        }
        
        public System.Threading.Tasks.Task<vp_webservice_documenttasks.setEntryProcessedSuccessResponse> setEntryProcessedSuccessAsync(string sessionId, long queueEntryId)
        {
            vp_webservice_documenttasks.setEntryProcessedSuccess inValue = new vp_webservice_documenttasks.setEntryProcessedSuccess();
            inValue.sessionId = sessionId;
            inValue.queueEntryId = queueEntryId;
            return ((vp_webservice_documenttasks.TaskQueues)(this)).setEntryProcessedSuccessAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TaskQueuesPort))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TaskQueuesPort))
            {
                return new System.ServiceModel.EndpointAddress("https://poc.virtualpostman.co.za/external/webservices/SOAP/TaskQueues-v1.0");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TaskQueuesClient.GetBindingForEndpoint(EndpointConfiguration.TaskQueuesPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TaskQueuesClient.GetEndpointAddress(EndpointConfiguration.TaskQueuesPort);
        }
        
        public enum EndpointConfiguration
        {
            
            TaskQueuesPort,
        }
    }
}
