//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vp_webservice_documents
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/")]
    public partial class Authorization
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/")]
    public partial class ViewKeyInformation
    {
        
        private string urlPrefixField;
        
        private string viewKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string urlPrefix
        {
            get
            {
                return this.urlPrefixField;
            }
            set
            {
                this.urlPrefixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string viewKey
        {
            get
            {
                return this.viewKeyField;
            }
            set
            {
                this.viewKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/")]
    public partial class InvalidArgument
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/")]
    public partial class Authentication
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/")]
    public partial class InputOutput
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", ConfigurationName="vp_webservice_documents.Documents")]
    public interface Documents
    {
        
        // CODEGEN: Parameter 'viewKeyInformation' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.Authorization), Action="", Name="Authorization")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.InvalidArgument), Action="", Name="InvalidArgument")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.Authentication), Action="", Name="Authentication")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="viewKeyInformation")]
        vp_webservice_documents.getMultipleDocumentsViewKeyResponse getMultipleDocumentsViewKey(vp_webservice_documents.getMultipleDocumentsViewKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<vp_webservice_documents.getMultipleDocumentsViewKeyResponse> getMultipleDocumentsViewKeyAsync(vp_webservice_documents.getMultipleDocumentsViewKey request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.Authorization), Action="", Name="Authorization")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.InvalidArgument), Action="", Name="InvalidArgument")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.Authentication), Action="", Name="Authentication")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        vp_webservice_documents.findDocumentsResponse findDocuments(vp_webservice_documents.findDocuments request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<vp_webservice_documents.findDocumentsResponse> findDocumentsAsync(vp_webservice_documents.findDocuments request);
        
        // CODEGEN: Parameter 'sourceDocument' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.Authorization), Action="", Name="Authorization")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.InvalidArgument), Action="", Name="InvalidArgument")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.Authentication), Action="", Name="Authentication")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="sourceDocument")]
        vp_webservice_documents.getSourceDocumentResponse getSourceDocument(vp_webservice_documents.getSourceDocument request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<vp_webservice_documents.getSourceDocumentResponse> getSourceDocumentAsync(vp_webservice_documents.getSourceDocument request);
        
        // CODEGEN: Parameter 'document' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.Authorization), Action="", Name="Authorization")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.InvalidArgument), Action="", Name="InvalidArgument")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.Authentication), Action="", Name="Authentication")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="document")]
        vp_webservice_documents.getDocumentResponse getDocument(vp_webservice_documents.getDocument request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<vp_webservice_documents.getDocumentResponse> getDocumentAsync(vp_webservice_documents.getDocument request);
        
        // CODEGEN: Parameter 'sessionId' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.Authorization), Action="", Name="Authorization")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.InputOutput), Action="", Name="InputOutput")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.InvalidArgument), Action="", Name="InvalidArgument")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.Authentication), Action="", Name="Authentication")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        vp_webservice_documents.deleteDocumentResponse deleteDocument(vp_webservice_documents.deleteDocument request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<vp_webservice_documents.deleteDocumentResponse> deleteDocumentAsync(vp_webservice_documents.deleteDocument request);
        
        // CODEGEN: Parameter 'documentContent' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.Authorization), Action="", Name="Authorization")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.InputOutput), Action="", Name="InputOutput")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.InvalidArgument), Action="", Name="InvalidArgument")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.Authentication), Action="", Name="Authentication")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="documentContent")]
        vp_webservice_documents.getDocumentContentAsPdfResponse getDocumentContentAsPdf(vp_webservice_documents.getDocumentContentAsPdf request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<vp_webservice_documents.getDocumentContentAsPdfResponse> getDocumentContentAsPdfAsync(vp_webservice_documents.getDocumentContentAsPdf request);
        
        // CODEGEN: Parameter 'viewKeyInformation' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.Authorization), Action="", Name="Authorization")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.InvalidArgument), Action="", Name="InvalidArgument")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.Authentication), Action="", Name="Authentication")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="viewKeyInformation")]
        vp_webservice_documents.getDocumentViewKeyResponse getDocumentViewKey(vp_webservice_documents.getDocumentViewKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<vp_webservice_documents.getDocumentViewKeyResponse> getDocumentViewKeyAsync(vp_webservice_documents.getDocumentViewKey request);
        
        // CODEGEN: Parameter 'sessionId' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.Authorization), Action="", Name="Authorization")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.InvalidArgument), Action="", Name="InvalidArgument")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.Authentication), Action="", Name="Authentication")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        vp_webservice_documents.setSourceDocumentResponse setSourceDocument(vp_webservice_documents.setSourceDocument request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<vp_webservice_documents.setSourceDocumentResponse> setSourceDocumentAsync(vp_webservice_documents.setSourceDocument request);
        
        // CODEGEN: Parameter 'documentContent' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.Authorization), Action="", Name="Authorization")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.InputOutput), Action="", Name="InputOutput")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.InvalidArgument), Action="", Name="InvalidArgument")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.Authentication), Action="", Name="Authentication")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="documentContent")]
        vp_webservice_documents.getDocumentContentResponse getDocumentContent(vp_webservice_documents.getDocumentContent request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<vp_webservice_documents.getDocumentContentResponse> getDocumentContentAsync(vp_webservice_documents.getDocumentContent request);
        
        // CODEGEN: Parameter 'sourceDocument' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.Authorization), Action="", Name="Authorization")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.InvalidArgument), Action="", Name="InvalidArgument")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.Authentication), Action="", Name="Authentication")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="sourceDocument")]
        vp_webservice_documents.getDerivedDocumentsResponse getDerivedDocuments(vp_webservice_documents.getDerivedDocuments request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<vp_webservice_documents.getDerivedDocumentsResponse> getDerivedDocumentsAsync(vp_webservice_documents.getDerivedDocuments request);
        
        // CODEGEN: Parameter 'archiveUserName' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.Authorization), Action="", Name="Authorization")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.InvalidArgument), Action="", Name="InvalidArgument")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.Authentication), Action="", Name="Authentication")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="archiveUserName")]
        vp_webservice_documents.getDocumentArchiveUserNameResponse getDocumentArchiveUserName(vp_webservice_documents.getDocumentArchiveUserName request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<vp_webservice_documents.getDocumentArchiveUserNameResponse> getDocumentArchiveUserNameAsync(vp_webservice_documents.getDocumentArchiveUserName request);
        
        // CODEGEN: Parameter 'documentImages' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.Authorization), Action="", Name="Authorization")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.InputOutput), Action="", Name="InputOutput")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.InvalidArgument), Action="", Name="InvalidArgument")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.Authentication), Action="", Name="Authentication")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="documentImages")]
        vp_webservice_documents.getDocumentContentAsImageResponse getDocumentContentAsImage(vp_webservice_documents.getDocumentContentAsImage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<vp_webservice_documents.getDocumentContentAsImageResponse> getDocumentContentAsImageAsync(vp_webservice_documents.getDocumentContentAsImage request);
        
        // CODEGEN: Parameter 'canConvertToPdf' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.Authorization), Action="", Name="Authorization")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.InvalidArgument), Action="", Name="InvalidArgument")]
        [System.ServiceModel.FaultContractAttribute(typeof(vp_webservice_documents.Authentication), Action="", Name="Authentication")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="canConvertToPdf")]
        vp_webservice_documents.canConvertDocumentToPdfResponse canConvertDocumentToPdf(vp_webservice_documents.canConvertDocumentToPdf request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<vp_webservice_documents.canConvertDocumentToPdfResponse> canConvertDocumentToPdfAsync(vp_webservice_documents.canConvertDocumentToPdf request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMultipleDocumentsViewKey", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", IsWrapped=true)]
    public partial class getMultipleDocumentsViewKey
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("documentId", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] documentId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int timeoutSeconds;
        
        public getMultipleDocumentsViewKey()
        {
        }
        
        public getMultipleDocumentsViewKey(string sessionId, long[] documentId, int timeoutSeconds)
        {
            this.sessionId = sessionId;
            this.documentId = documentId;
            this.timeoutSeconds = timeoutSeconds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMultipleDocumentsViewKeyResponse", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", IsWrapped=true)]
    public partial class getMultipleDocumentsViewKeyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public vp_webservice_documents.ViewKeyInformation viewKeyInformation;
        
        public getMultipleDocumentsViewKeyResponse()
        {
        }
        
        public getMultipleDocumentsViewKeyResponse(vp_webservice_documents.ViewKeyInformation viewKeyInformation)
        {
            this.viewKeyInformation = viewKeyInformation;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/")]
    public partial class indexValue
    {
        
        private string indexNameField;
        
        private string indexValue1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string indexName
        {
            get
            {
                return this.indexNameField;
            }
            set
            {
                this.indexNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("indexValue", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string indexValue1
        {
            get
            {
                return this.indexValue1Field;
            }
            set
            {
                this.indexValue1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/")]
    public partial class document
    {
        
        private long idField;
        
        private string nodeNameField;
        
        private string originalFileNameField;
        
        private string contentTypeField;
        
        private System.DateTime archiveDateField;
        
        private bool archiveDateFieldSpecified;
        
        private indexValue[] indexValuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nodeName
        {
            get
            {
                return this.nodeNameField;
            }
            set
            {
                this.nodeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string originalFileName
        {
            get
            {
                return this.originalFileNameField;
            }
            set
            {
                this.originalFileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string contentType
        {
            get
            {
                return this.contentTypeField;
            }
            set
            {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime archiveDate
        {
            get
            {
                return this.archiveDateField;
            }
            set
            {
                this.archiveDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool archiveDateSpecified
        {
            get
            {
                return this.archiveDateFieldSpecified;
            }
            set
            {
                this.archiveDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("indexValues", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public indexValue[] indexValues
        {
            get
            {
                return this.indexValuesField;
            }
            set
            {
                this.indexValuesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findDocuments", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", IsWrapped=true)]
    public partial class findDocuments
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nameName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("indexValues", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public vp_webservice_documents.indexValue[] indexValues;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime startDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime endDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int pagingOffset;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int pagingLimit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sortIndexName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool sortDescending;
        
        public findDocuments()
        {
        }
        
        public findDocuments(string sessionId, string nameName, vp_webservice_documents.indexValue[] indexValues, System.DateTime startDate, System.DateTime endDate, int pagingOffset, int pagingLimit, string sortIndexName, bool sortDescending)
        {
            this.sessionId = sessionId;
            this.nameName = nameName;
            this.indexValues = indexValues;
            this.startDate = startDate;
            this.endDate = endDate;
            this.pagingOffset = pagingOffset;
            this.pagingLimit = pagingLimit;
            this.sortIndexName = sortIndexName;
            this.sortDescending = sortDescending;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findDocumentsResponse", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", IsWrapped=true)]
    public partial class findDocumentsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public vp_webservice_documents.document[] @return;
        
        public findDocumentsResponse()
        {
        }
        
        public findDocumentsResponse(vp_webservice_documents.document[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSourceDocument", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", IsWrapped=true)]
    public partial class getSourceDocument
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long documentId;
        
        public getSourceDocument()
        {
        }
        
        public getSourceDocument(string sessionId, long documentId)
        {
            this.sessionId = sessionId;
            this.documentId = documentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSourceDocumentResponse", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", IsWrapped=true)]
    public partial class getSourceDocumentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public vp_webservice_documents.document sourceDocument;
        
        public getSourceDocumentResponse()
        {
        }
        
        public getSourceDocumentResponse(vp_webservice_documents.document sourceDocument)
        {
            this.sourceDocument = sourceDocument;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDocument", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", IsWrapped=true)]
    public partial class getDocument
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long documentId;
        
        public getDocument()
        {
        }
        
        public getDocument(string sessionId, long documentId)
        {
            this.sessionId = sessionId;
            this.documentId = documentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDocumentResponse", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", IsWrapped=true)]
    public partial class getDocumentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public vp_webservice_documents.document document;
        
        public getDocumentResponse()
        {
        }
        
        public getDocumentResponse(vp_webservice_documents.document document)
        {
            this.document = document;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteDocument", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", IsWrapped=true)]
    public partial class deleteDocument
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long documentId;
        
        public deleteDocument()
        {
        }
        
        public deleteDocument(string sessionId, long documentId)
        {
            this.sessionId = sessionId;
            this.documentId = documentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteDocumentResponse", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", IsWrapped=true)]
    public partial class deleteDocumentResponse
    {
        
        public deleteDocumentResponse()
        {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/")]
    public partial class DocumentContent
    {
        
        private string mimeTypeField;
        
        private byte[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mimeType
        {
            get
            {
                return this.mimeTypeField;
            }
            set
            {
                this.mimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDocumentContentAsPdf", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", IsWrapped=true)]
    public partial class getDocumentContentAsPdf
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long documentId;
        
        public getDocumentContentAsPdf()
        {
        }
        
        public getDocumentContentAsPdf(string sessionId, long documentId)
        {
            this.sessionId = sessionId;
            this.documentId = documentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDocumentContentAsPdfResponse", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", IsWrapped=true)]
    public partial class getDocumentContentAsPdfResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public vp_webservice_documents.DocumentContent documentContent;
        
        public getDocumentContentAsPdfResponse()
        {
        }
        
        public getDocumentContentAsPdfResponse(vp_webservice_documents.DocumentContent documentContent)
        {
            this.documentContent = documentContent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDocumentViewKey", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", IsWrapped=true)]
    public partial class getDocumentViewKey
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long documentId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int timeoutSeconds;
        
        public getDocumentViewKey()
        {
        }
        
        public getDocumentViewKey(string sessionId, long documentId, int timeoutSeconds)
        {
            this.sessionId = sessionId;
            this.documentId = documentId;
            this.timeoutSeconds = timeoutSeconds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDocumentViewKeyResponse", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", IsWrapped=true)]
    public partial class getDocumentViewKeyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public vp_webservice_documents.ViewKeyInformation viewKeyInformation;
        
        public getDocumentViewKeyResponse()
        {
        }
        
        public getDocumentViewKeyResponse(vp_webservice_documents.ViewKeyInformation viewKeyInformation)
        {
            this.viewKeyInformation = viewKeyInformation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setSourceDocument", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", IsWrapped=true)]
    public partial class setSourceDocument
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long documentId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long sourceDocumentId;
        
        public setSourceDocument()
        {
        }
        
        public setSourceDocument(string sessionId, long documentId, long sourceDocumentId)
        {
            this.sessionId = sessionId;
            this.documentId = documentId;
            this.sourceDocumentId = sourceDocumentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setSourceDocumentResponse", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", IsWrapped=true)]
    public partial class setSourceDocumentResponse
    {
        
        public setSourceDocumentResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDocumentContent", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", IsWrapped=true)]
    public partial class getDocumentContent
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long documentId;
        
        public getDocumentContent()
        {
        }
        
        public getDocumentContent(string sessionId, long documentId)
        {
            this.sessionId = sessionId;
            this.documentId = documentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDocumentContentResponse", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", IsWrapped=true)]
    public partial class getDocumentContentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public vp_webservice_documents.DocumentContent documentContent;
        
        public getDocumentContentResponse()
        {
        }
        
        public getDocumentContentResponse(vp_webservice_documents.DocumentContent documentContent)
        {
            this.documentContent = documentContent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDerivedDocuments", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", IsWrapped=true)]
    public partial class getDerivedDocuments
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long documentId;
        
        public getDerivedDocuments()
        {
        }
        
        public getDerivedDocuments(string sessionId, long documentId)
        {
            this.sessionId = sessionId;
            this.documentId = documentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDerivedDocumentsResponse", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", IsWrapped=true)]
    public partial class getDerivedDocumentsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("sourceDocument", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public vp_webservice_documents.document[] sourceDocument;
        
        public getDerivedDocumentsResponse()
        {
        }
        
        public getDerivedDocumentsResponse(vp_webservice_documents.document[] sourceDocument)
        {
            this.sourceDocument = sourceDocument;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDocumentArchiveUserName", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", IsWrapped=true)]
    public partial class getDocumentArchiveUserName
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long documentId;
        
        public getDocumentArchiveUserName()
        {
        }
        
        public getDocumentArchiveUserName(string sessionId, long documentId)
        {
            this.sessionId = sessionId;
            this.documentId = documentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDocumentArchiveUserNameResponse", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", IsWrapped=true)]
    public partial class getDocumentArchiveUserNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string archiveUserName;
        
        public getDocumentArchiveUserNameResponse()
        {
        }
        
        public getDocumentArchiveUserNameResponse(string archiveUserName)
        {
            this.archiveUserName = archiveUserName;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/")]
    public enum imageFormat
    {
        
        /// <remarks/>
        JPEG,
        
        /// <remarks/>
        PNG,
        
        /// <remarks/>
        TIFF,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/")]
    public enum colorMode
    {
        
        /// <remarks/>
        NO_RESTRICTION,
        
        /// <remarks/>
        GRAYSCALE,
        
        /// <remarks/>
        BLACK_AND_WHITE,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDocumentContentAsImage", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", IsWrapped=true)]
    public partial class getDocumentContentAsImage
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long documentId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public vp_webservice_documents.imageFormat imageFormat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public vp_webservice_documents.colorMode colorMode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int dpi;
        
        public getDocumentContentAsImage()
        {
        }
        
        public getDocumentContentAsImage(string sessionId, long documentId, vp_webservice_documents.imageFormat imageFormat, vp_webservice_documents.colorMode colorMode, int dpi)
        {
            this.sessionId = sessionId;
            this.documentId = documentId;
            this.imageFormat = imageFormat;
            this.colorMode = colorMode;
            this.dpi = dpi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDocumentContentAsImageResponse", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", IsWrapped=true)]
    public partial class getDocumentContentAsImageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("documentImages", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public vp_webservice_documents.DocumentContent[] documentImages;
        
        public getDocumentContentAsImageResponse()
        {
        }
        
        public getDocumentContentAsImageResponse(vp_webservice_documents.DocumentContent[] documentImages)
        {
            this.documentImages = documentImages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="canConvertDocumentToPdf", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", IsWrapped=true)]
    public partial class canConvertDocumentToPdf
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long documentId;
        
        public canConvertDocumentToPdf()
        {
        }
        
        public canConvertDocumentToPdf(string sessionId, long documentId)
        {
            this.sessionId = sessionId;
            this.documentId = documentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="canConvertDocumentToPdfResponse", WrapperNamespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", IsWrapped=true)]
    public partial class canConvertDocumentToPdfResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://virtualpostman.co.za/vp/webservices/Documents/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool canConvertToPdf;
        
        public canConvertDocumentToPdfResponse()
        {
        }
        
        public canConvertDocumentToPdfResponse(bool canConvertToPdf)
        {
            this.canConvertToPdf = canConvertToPdf;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface DocumentsChannel : vp_webservice_documents.Documents, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class DocumentsClient : System.ServiceModel.ClientBase<vp_webservice_documents.Documents>, vp_webservice_documents.Documents
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DocumentsClient() : 
                base(DocumentsClient.GetDefaultBinding(), DocumentsClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.DocumentsPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocumentsClient(EndpointConfiguration endpointConfiguration) : 
                base(DocumentsClient.GetBindingForEndpoint(endpointConfiguration), DocumentsClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocumentsClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DocumentsClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocumentsClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DocumentsClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocumentsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        vp_webservice_documents.getMultipleDocumentsViewKeyResponse vp_webservice_documents.Documents.getMultipleDocumentsViewKey(vp_webservice_documents.getMultipleDocumentsViewKey request)
        {
            return base.Channel.getMultipleDocumentsViewKey(request);
        }
        
        public vp_webservice_documents.ViewKeyInformation getMultipleDocumentsViewKey(string sessionId, long[] documentId, int timeoutSeconds)
        {
            vp_webservice_documents.getMultipleDocumentsViewKey inValue = new vp_webservice_documents.getMultipleDocumentsViewKey();
            inValue.sessionId = sessionId;
            inValue.documentId = documentId;
            inValue.timeoutSeconds = timeoutSeconds;
            vp_webservice_documents.getMultipleDocumentsViewKeyResponse retVal = ((vp_webservice_documents.Documents)(this)).getMultipleDocumentsViewKey(inValue);
            return retVal.viewKeyInformation;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<vp_webservice_documents.getMultipleDocumentsViewKeyResponse> vp_webservice_documents.Documents.getMultipleDocumentsViewKeyAsync(vp_webservice_documents.getMultipleDocumentsViewKey request)
        {
            return base.Channel.getMultipleDocumentsViewKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<vp_webservice_documents.getMultipleDocumentsViewKeyResponse> getMultipleDocumentsViewKeyAsync(string sessionId, long[] documentId, int timeoutSeconds)
        {
            vp_webservice_documents.getMultipleDocumentsViewKey inValue = new vp_webservice_documents.getMultipleDocumentsViewKey();
            inValue.sessionId = sessionId;
            inValue.documentId = documentId;
            inValue.timeoutSeconds = timeoutSeconds;
            return ((vp_webservice_documents.Documents)(this)).getMultipleDocumentsViewKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        vp_webservice_documents.findDocumentsResponse vp_webservice_documents.Documents.findDocuments(vp_webservice_documents.findDocuments request)
        {
            return base.Channel.findDocuments(request);
        }
        
        public vp_webservice_documents.document[] findDocuments(string sessionId, string nameName, vp_webservice_documents.indexValue[] indexValues, System.DateTime startDate, System.DateTime endDate, int pagingOffset, int pagingLimit, string sortIndexName, bool sortDescending)
        {
            vp_webservice_documents.findDocuments inValue = new vp_webservice_documents.findDocuments();
            inValue.sessionId = sessionId;
            inValue.nameName = nameName;
            inValue.indexValues = indexValues;
            inValue.startDate = startDate;
            inValue.endDate = endDate;
            inValue.pagingOffset = pagingOffset;
            inValue.pagingLimit = pagingLimit;
            inValue.sortIndexName = sortIndexName;
            inValue.sortDescending = sortDescending;
            vp_webservice_documents.findDocumentsResponse retVal = ((vp_webservice_documents.Documents)(this)).findDocuments(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<vp_webservice_documents.findDocumentsResponse> vp_webservice_documents.Documents.findDocumentsAsync(vp_webservice_documents.findDocuments request)
        {
            return base.Channel.findDocumentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<vp_webservice_documents.findDocumentsResponse> findDocumentsAsync(string sessionId, string nameName, vp_webservice_documents.indexValue[] indexValues, System.DateTime startDate, System.DateTime endDate, int pagingOffset, int pagingLimit, string sortIndexName, bool sortDescending)
        {
            vp_webservice_documents.findDocuments inValue = new vp_webservice_documents.findDocuments();
            inValue.sessionId = sessionId;
            inValue.nameName = nameName;
            inValue.indexValues = indexValues;
            inValue.startDate = startDate;
            inValue.endDate = endDate;
            inValue.pagingOffset = pagingOffset;
            inValue.pagingLimit = pagingLimit;
            inValue.sortIndexName = sortIndexName;
            inValue.sortDescending = sortDescending;
            return ((vp_webservice_documents.Documents)(this)).findDocumentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        vp_webservice_documents.getSourceDocumentResponse vp_webservice_documents.Documents.getSourceDocument(vp_webservice_documents.getSourceDocument request)
        {
            return base.Channel.getSourceDocument(request);
        }
        
        public vp_webservice_documents.document getSourceDocument(string sessionId, long documentId)
        {
            vp_webservice_documents.getSourceDocument inValue = new vp_webservice_documents.getSourceDocument();
            inValue.sessionId = sessionId;
            inValue.documentId = documentId;
            vp_webservice_documents.getSourceDocumentResponse retVal = ((vp_webservice_documents.Documents)(this)).getSourceDocument(inValue);
            return retVal.sourceDocument;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<vp_webservice_documents.getSourceDocumentResponse> vp_webservice_documents.Documents.getSourceDocumentAsync(vp_webservice_documents.getSourceDocument request)
        {
            return base.Channel.getSourceDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<vp_webservice_documents.getSourceDocumentResponse> getSourceDocumentAsync(string sessionId, long documentId)
        {
            vp_webservice_documents.getSourceDocument inValue = new vp_webservice_documents.getSourceDocument();
            inValue.sessionId = sessionId;
            inValue.documentId = documentId;
            return ((vp_webservice_documents.Documents)(this)).getSourceDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        vp_webservice_documents.getDocumentResponse vp_webservice_documents.Documents.getDocument(vp_webservice_documents.getDocument request)
        {
            return base.Channel.getDocument(request);
        }
        
        public vp_webservice_documents.document getDocument(string sessionId, long documentId)
        {
            vp_webservice_documents.getDocument inValue = new vp_webservice_documents.getDocument();
            inValue.sessionId = sessionId;
            inValue.documentId = documentId;
            vp_webservice_documents.getDocumentResponse retVal = ((vp_webservice_documents.Documents)(this)).getDocument(inValue);
            return retVal.document;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<vp_webservice_documents.getDocumentResponse> vp_webservice_documents.Documents.getDocumentAsync(vp_webservice_documents.getDocument request)
        {
            return base.Channel.getDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<vp_webservice_documents.getDocumentResponse> getDocumentAsync(string sessionId, long documentId)
        {
            vp_webservice_documents.getDocument inValue = new vp_webservice_documents.getDocument();
            inValue.sessionId = sessionId;
            inValue.documentId = documentId;
            return ((vp_webservice_documents.Documents)(this)).getDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        vp_webservice_documents.deleteDocumentResponse vp_webservice_documents.Documents.deleteDocument(vp_webservice_documents.deleteDocument request)
        {
            return base.Channel.deleteDocument(request);
        }
        
        public void deleteDocument(string sessionId, long documentId)
        {
            vp_webservice_documents.deleteDocument inValue = new vp_webservice_documents.deleteDocument();
            inValue.sessionId = sessionId;
            inValue.documentId = documentId;
            vp_webservice_documents.deleteDocumentResponse retVal = ((vp_webservice_documents.Documents)(this)).deleteDocument(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<vp_webservice_documents.deleteDocumentResponse> vp_webservice_documents.Documents.deleteDocumentAsync(vp_webservice_documents.deleteDocument request)
        {
            return base.Channel.deleteDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<vp_webservice_documents.deleteDocumentResponse> deleteDocumentAsync(string sessionId, long documentId)
        {
            vp_webservice_documents.deleteDocument inValue = new vp_webservice_documents.deleteDocument();
            inValue.sessionId = sessionId;
            inValue.documentId = documentId;
            return ((vp_webservice_documents.Documents)(this)).deleteDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        vp_webservice_documents.getDocumentContentAsPdfResponse vp_webservice_documents.Documents.getDocumentContentAsPdf(vp_webservice_documents.getDocumentContentAsPdf request)
        {
            return base.Channel.getDocumentContentAsPdf(request);
        }
        
        public vp_webservice_documents.DocumentContent getDocumentContentAsPdf(string sessionId, long documentId)
        {
            vp_webservice_documents.getDocumentContentAsPdf inValue = new vp_webservice_documents.getDocumentContentAsPdf();
            inValue.sessionId = sessionId;
            inValue.documentId = documentId;
            vp_webservice_documents.getDocumentContentAsPdfResponse retVal = ((vp_webservice_documents.Documents)(this)).getDocumentContentAsPdf(inValue);
            return retVal.documentContent;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<vp_webservice_documents.getDocumentContentAsPdfResponse> vp_webservice_documents.Documents.getDocumentContentAsPdfAsync(vp_webservice_documents.getDocumentContentAsPdf request)
        {
            return base.Channel.getDocumentContentAsPdfAsync(request);
        }
        
        public System.Threading.Tasks.Task<vp_webservice_documents.getDocumentContentAsPdfResponse> getDocumentContentAsPdfAsync(string sessionId, long documentId)
        {
            vp_webservice_documents.getDocumentContentAsPdf inValue = new vp_webservice_documents.getDocumentContentAsPdf();
            inValue.sessionId = sessionId;
            inValue.documentId = documentId;
            return ((vp_webservice_documents.Documents)(this)).getDocumentContentAsPdfAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        vp_webservice_documents.getDocumentViewKeyResponse vp_webservice_documents.Documents.getDocumentViewKey(vp_webservice_documents.getDocumentViewKey request)
        {
            return base.Channel.getDocumentViewKey(request);
        }
        
        public vp_webservice_documents.ViewKeyInformation getDocumentViewKey(string sessionId, long documentId, int timeoutSeconds)
        {
            vp_webservice_documents.getDocumentViewKey inValue = new vp_webservice_documents.getDocumentViewKey();
            inValue.sessionId = sessionId;
            inValue.documentId = documentId;
            inValue.timeoutSeconds = timeoutSeconds;
            vp_webservice_documents.getDocumentViewKeyResponse retVal = ((vp_webservice_documents.Documents)(this)).getDocumentViewKey(inValue);
            return retVal.viewKeyInformation;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<vp_webservice_documents.getDocumentViewKeyResponse> vp_webservice_documents.Documents.getDocumentViewKeyAsync(vp_webservice_documents.getDocumentViewKey request)
        {
            return base.Channel.getDocumentViewKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<vp_webservice_documents.getDocumentViewKeyResponse> getDocumentViewKeyAsync(string sessionId, long documentId, int timeoutSeconds)
        {
            vp_webservice_documents.getDocumentViewKey inValue = new vp_webservice_documents.getDocumentViewKey();
            inValue.sessionId = sessionId;
            inValue.documentId = documentId;
            inValue.timeoutSeconds = timeoutSeconds;
            return ((vp_webservice_documents.Documents)(this)).getDocumentViewKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        vp_webservice_documents.setSourceDocumentResponse vp_webservice_documents.Documents.setSourceDocument(vp_webservice_documents.setSourceDocument request)
        {
            return base.Channel.setSourceDocument(request);
        }
        
        public void setSourceDocument(string sessionId, long documentId, long sourceDocumentId)
        {
            vp_webservice_documents.setSourceDocument inValue = new vp_webservice_documents.setSourceDocument();
            inValue.sessionId = sessionId;
            inValue.documentId = documentId;
            inValue.sourceDocumentId = sourceDocumentId;
            vp_webservice_documents.setSourceDocumentResponse retVal = ((vp_webservice_documents.Documents)(this)).setSourceDocument(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<vp_webservice_documents.setSourceDocumentResponse> vp_webservice_documents.Documents.setSourceDocumentAsync(vp_webservice_documents.setSourceDocument request)
        {
            return base.Channel.setSourceDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<vp_webservice_documents.setSourceDocumentResponse> setSourceDocumentAsync(string sessionId, long documentId, long sourceDocumentId)
        {
            vp_webservice_documents.setSourceDocument inValue = new vp_webservice_documents.setSourceDocument();
            inValue.sessionId = sessionId;
            inValue.documentId = documentId;
            inValue.sourceDocumentId = sourceDocumentId;
            return ((vp_webservice_documents.Documents)(this)).setSourceDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        vp_webservice_documents.getDocumentContentResponse vp_webservice_documents.Documents.getDocumentContent(vp_webservice_documents.getDocumentContent request)
        {
            return base.Channel.getDocumentContent(request);
        }
        
        public vp_webservice_documents.DocumentContent getDocumentContent(string sessionId, long documentId)
        {
            vp_webservice_documents.getDocumentContent inValue = new vp_webservice_documents.getDocumentContent();
            inValue.sessionId = sessionId;
            inValue.documentId = documentId;
            vp_webservice_documents.getDocumentContentResponse retVal = ((vp_webservice_documents.Documents)(this)).getDocumentContent(inValue);
            return retVal.documentContent;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<vp_webservice_documents.getDocumentContentResponse> vp_webservice_documents.Documents.getDocumentContentAsync(vp_webservice_documents.getDocumentContent request)
        {
            return base.Channel.getDocumentContentAsync(request);
        }
        
        public System.Threading.Tasks.Task<vp_webservice_documents.getDocumentContentResponse> getDocumentContentAsync(string sessionId, long documentId)
        {
            vp_webservice_documents.getDocumentContent inValue = new vp_webservice_documents.getDocumentContent();
            inValue.sessionId = sessionId;
            inValue.documentId = documentId;
            return ((vp_webservice_documents.Documents)(this)).getDocumentContentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        vp_webservice_documents.getDerivedDocumentsResponse vp_webservice_documents.Documents.getDerivedDocuments(vp_webservice_documents.getDerivedDocuments request)
        {
            return base.Channel.getDerivedDocuments(request);
        }
        
        public vp_webservice_documents.document[] getDerivedDocuments(string sessionId, long documentId)
        {
            vp_webservice_documents.getDerivedDocuments inValue = new vp_webservice_documents.getDerivedDocuments();
            inValue.sessionId = sessionId;
            inValue.documentId = documentId;
            vp_webservice_documents.getDerivedDocumentsResponse retVal = ((vp_webservice_documents.Documents)(this)).getDerivedDocuments(inValue);
            return retVal.sourceDocument;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<vp_webservice_documents.getDerivedDocumentsResponse> vp_webservice_documents.Documents.getDerivedDocumentsAsync(vp_webservice_documents.getDerivedDocuments request)
        {
            return base.Channel.getDerivedDocumentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<vp_webservice_documents.getDerivedDocumentsResponse> getDerivedDocumentsAsync(string sessionId, long documentId)
        {
            vp_webservice_documents.getDerivedDocuments inValue = new vp_webservice_documents.getDerivedDocuments();
            inValue.sessionId = sessionId;
            inValue.documentId = documentId;
            return ((vp_webservice_documents.Documents)(this)).getDerivedDocumentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        vp_webservice_documents.getDocumentArchiveUserNameResponse vp_webservice_documents.Documents.getDocumentArchiveUserName(vp_webservice_documents.getDocumentArchiveUserName request)
        {
            return base.Channel.getDocumentArchiveUserName(request);
        }
        
        public string getDocumentArchiveUserName(string sessionId, long documentId)
        {
            vp_webservice_documents.getDocumentArchiveUserName inValue = new vp_webservice_documents.getDocumentArchiveUserName();
            inValue.sessionId = sessionId;
            inValue.documentId = documentId;
            vp_webservice_documents.getDocumentArchiveUserNameResponse retVal = ((vp_webservice_documents.Documents)(this)).getDocumentArchiveUserName(inValue);
            return retVal.archiveUserName;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<vp_webservice_documents.getDocumentArchiveUserNameResponse> vp_webservice_documents.Documents.getDocumentArchiveUserNameAsync(vp_webservice_documents.getDocumentArchiveUserName request)
        {
            return base.Channel.getDocumentArchiveUserNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<vp_webservice_documents.getDocumentArchiveUserNameResponse> getDocumentArchiveUserNameAsync(string sessionId, long documentId)
        {
            vp_webservice_documents.getDocumentArchiveUserName inValue = new vp_webservice_documents.getDocumentArchiveUserName();
            inValue.sessionId = sessionId;
            inValue.documentId = documentId;
            return ((vp_webservice_documents.Documents)(this)).getDocumentArchiveUserNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        vp_webservice_documents.getDocumentContentAsImageResponse vp_webservice_documents.Documents.getDocumentContentAsImage(vp_webservice_documents.getDocumentContentAsImage request)
        {
            return base.Channel.getDocumentContentAsImage(request);
        }
        
        public vp_webservice_documents.DocumentContent[] getDocumentContentAsImage(string sessionId, long documentId, vp_webservice_documents.imageFormat imageFormat, vp_webservice_documents.colorMode colorMode, int dpi)
        {
            vp_webservice_documents.getDocumentContentAsImage inValue = new vp_webservice_documents.getDocumentContentAsImage();
            inValue.sessionId = sessionId;
            inValue.documentId = documentId;
            inValue.imageFormat = imageFormat;
            inValue.colorMode = colorMode;
            inValue.dpi = dpi;
            vp_webservice_documents.getDocumentContentAsImageResponse retVal = ((vp_webservice_documents.Documents)(this)).getDocumentContentAsImage(inValue);
            return retVal.documentImages;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<vp_webservice_documents.getDocumentContentAsImageResponse> vp_webservice_documents.Documents.getDocumentContentAsImageAsync(vp_webservice_documents.getDocumentContentAsImage request)
        {
            return base.Channel.getDocumentContentAsImageAsync(request);
        }
        
        public System.Threading.Tasks.Task<vp_webservice_documents.getDocumentContentAsImageResponse> getDocumentContentAsImageAsync(string sessionId, long documentId, vp_webservice_documents.imageFormat imageFormat, vp_webservice_documents.colorMode colorMode, int dpi)
        {
            vp_webservice_documents.getDocumentContentAsImage inValue = new vp_webservice_documents.getDocumentContentAsImage();
            inValue.sessionId = sessionId;
            inValue.documentId = documentId;
            inValue.imageFormat = imageFormat;
            inValue.colorMode = colorMode;
            inValue.dpi = dpi;
            return ((vp_webservice_documents.Documents)(this)).getDocumentContentAsImageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        vp_webservice_documents.canConvertDocumentToPdfResponse vp_webservice_documents.Documents.canConvertDocumentToPdf(vp_webservice_documents.canConvertDocumentToPdf request)
        {
            return base.Channel.canConvertDocumentToPdf(request);
        }
        
        public bool canConvertDocumentToPdf(string sessionId, long documentId)
        {
            vp_webservice_documents.canConvertDocumentToPdf inValue = new vp_webservice_documents.canConvertDocumentToPdf();
            inValue.sessionId = sessionId;
            inValue.documentId = documentId;
            vp_webservice_documents.canConvertDocumentToPdfResponse retVal = ((vp_webservice_documents.Documents)(this)).canConvertDocumentToPdf(inValue);
            return retVal.canConvertToPdf;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<vp_webservice_documents.canConvertDocumentToPdfResponse> vp_webservice_documents.Documents.canConvertDocumentToPdfAsync(vp_webservice_documents.canConvertDocumentToPdf request)
        {
            return base.Channel.canConvertDocumentToPdfAsync(request);
        }
        
        public System.Threading.Tasks.Task<vp_webservice_documents.canConvertDocumentToPdfResponse> canConvertDocumentToPdfAsync(string sessionId, long documentId)
        {
            vp_webservice_documents.canConvertDocumentToPdf inValue = new vp_webservice_documents.canConvertDocumentToPdf();
            inValue.sessionId = sessionId;
            inValue.documentId = documentId;
            return ((vp_webservice_documents.Documents)(this)).canConvertDocumentToPdfAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DocumentsPort))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DocumentsPort))
            {
                return new System.ServiceModel.EndpointAddress("https://poc.virtualpostman.co.za/external/webservices/SOAP/Documents-v1.6");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DocumentsClient.GetBindingForEndpoint(EndpointConfiguration.DocumentsPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DocumentsClient.GetEndpointAddress(EndpointConfiguration.DocumentsPort);
        }
        
        public enum EndpointConfiguration
        {
            
            DocumentsPort,
        }
    }
}
